apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /study/kube/cy/test
