name: Cy Test

on: [push]

env:
  ARTIFACT_NAME: report

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Upload Report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./report/mochawesome
          
  use-artifacts:
    name: Use Artifacts
    runs-on: ubuntu-latest
    needs: [test]
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: ${{env.ARTIFACT_NAME}}
        
      - name: Check files
        run: |
          cd ${{env.ARTIFACT_NAME}}
          ls
  
  

